name: CI

on:
  pull_request:

  push:
    branches: [master]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Rubocop
        run: |
          gem install bundler
          bundle config set without 'development test'
          bundle config set with 'lint'
          bundle install
          bundle exec rubocop --format progress
  build:
    needs: [linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Test
        run: |
          bundle exec rake
